version: '3.0'

services:
  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
    - type: volume
      source: data
      target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  data: {}
